import localFont from "next/font/local";
import "./globals.css";

const JosefinSans = localFont({
  src: "./fonts/JosefinSans-VariableFont_wght.ttf",
  variable: "--font-josefin-sans",
  weight: "100 900",
});
const MarcellusMono = localFont({
  src: "./fonts/Marcellus-Regular.ttf",
  variable: "--font-Marcellus-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JosefinSans.variable} ${MarcellusMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
